import Head from 'next/head'
import InputArea from '../../components/input-area'

export default function Home() {
  return (
    <>
      <Head>
        <title>MovieMoji</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <h3 style={{marginBottom: '40px'}}>Movie to Emoji</h3>
        <InputArea/>
      </main>
      <footer className='footer'>
          <span className='footer-content'>
            Powered by <a href='https://chat.openai.com/chat'>ChatGPT</a> from <a href='https://platform.openai.com/overview'>OpenAI</a>
          </span>
      </footer>
    </>
  )
}
